const assert = require('node:assert/strict');
const { FormulaEditHistory } = require('../web/formula-edit');
const h = new FormulaEditHistory('SUM([x])');
assert.equal(h.dirty, false);
assert.equal(h.started, false);
h.push('SUM([x]) + 1');
assert.ok(h.dirty && h.canUndo && !h.canRedo);
h.undo();
assert.equal(h.source, 'SUM([x])');
assert.equal(h.dirty, false);
assert.ok(h.started && h.canRedo);
h.redo();
assert.equal(h.source, 'SUM([x]) + 1');
assert.ok(h.dirty);
h.undo();
h.push('SUM([x]) + 2');
assert.equal(h.canRedo, false);
h.reset(h.source);
assert.equal(h.dirty, false);
assert.equal(h.started, false);
assert.equal(h.canUndo, false);
console.log('Formula editor: dirty state, undo, redo, alternate edits, and saved baseline passed.');
const { FlowEditHistory } = require('../web/formula-edit');
const flow = new FlowEditHistory(),
  first = { field: 'A', before: '1', expression: '2' },
  second = { field: 'B', before: '3', expression: '4' };
assert.equal(flow.started, false);
flow.push(first);
flow.push(second);
assert.deepEqual(flow.changes, [first, second]);
flow.index--;
assert.deepEqual(flow.changes, [first]);
assert.ok(flow.canRedo);
flow.index--;
assert.equal(flow.dirty, false);
assert.ok(flow.canRedo && flow.started);
flow.index++;
flow.push({ ...second, expression: '5' });
assert.equal(flow.canRedo, false);
assert.equal(flow.changes[1].expression, '5');
flow.reset();
assert.equal(flow.started, false);
console.log('Flow history: cross-field undo/redo, branching, and saved reset passed.');
