const assert=require('node:assert/strict');
const {commentLayout,wrapStepComment}=require('../web/comment-layout.js');
const measure=s=>Array.from(s).length*12;
const node=(id,x,y,description='',height=1)=>({id,position:{x,y},description,display:{size:{height}}});
const nodes=[node('a',1,0,'あ'.repeat(30),2),node('a-input',0,0),node('b',1,2,'い'.repeat(16),2),node('c',5,4,'う'.repeat(200),4),node('last',5,8)];
const open=new Set(['a','b','c']);
const initial=commentLayout(nodes,open,measure);
assert.equal(initial.positions.get('last').y,70+8*117);
const closed=commentLayout(nodes,new Set(),measure);
assert.equal(closed.positions.get('last').y,70+3*117);
const one=commentLayout(nodes,new Set(['a']),measure);
assert.equal(one.positions.get('last').y,70+4*117);
assert.equal(one.positions.get('a').y,one.positions.get('a-input').y);
assert.equal(initial.positions.get('last').x,closed.positions.get('last').x);
assert.deepEqual(commentLayout(nodes,open,measure),initial,'Repeated toggles must not accumulate drift');
const plain=[node('p',0,0),node('q',1,5)];
assert.equal(commentLayout(plain,new Set(),measure).positions.get('q').y,70+5*117,'Keep unrelated saved gaps');
const shared=[node('a',0,0,'あ'.repeat(30),2),node('b',1,0,'い'.repeat(30),2),node('c',1,2)];
assert.equal(commentLayout(shared,new Set(['a','b']),measure).positions.get('c').y,70+2*117,'Shared row reserves space once');
assert.equal(commentLayout(shared,new Set(['b']),measure).positions.get('c').y,70+2*117,'Other open comments keep their space');
assert.deepEqual(wrapStepComment('one\r\n\n三😀',measure),['one','','三😀']);
assert.equal(wrapStepComment('<script> & '+ 'あ'.repeat(200),measure).join(''),'<script> & '+'あ'.repeat(200));
const bottom=commentLayout([nodes[2]],new Set(['b']),measure);
assert.ok(bottom.bounds.height>bottom.positions.get('b').y+bottom.comments.get('b').bottom);
console.log('Comment layout: saved spacing, independent toggles, shared rows, full text and bounds passed.');
const {graphTextArea,fitGraphText}=require('../web/comment-layout.js');
const longComment=Array.from({length:12},(_,i)=>`Line ${i+1}`).join('\n');
const textMeasure=text=>Array.from(text).length*6;
assert.equal(fitGraphText(longComment,textMeasure,140).length,12,'No fixed three-line cap when space is free');
const points=new Map([['a',{x:0,y:0}],['b',{x:0,y:400}],['side',{x:170,y:0}]]);
const area=graphTextArea('a',points,.5),top=100,lineHeight=22;
const allowed=Math.max(0,Math.floor((area.bottom-top)/lineHeight)+1);
const visible=fitGraphText(longComment,textMeasure,area.width,allowed);
assert.ok(visible.length>3,'Use the available space for more than three lines');
assert.ok(top+(visible.length-1)*lineHeight<=area.bottom,'Stop before the lower step');
assert.ok(visible.at(-1).endsWith('…'),'Mark truncated text');
assert.equal(graphTextArea('b',points,.5).bottom,Infinity,'Last step can show its whole comment');
assert.equal(fitGraphText('😀',s=>s==='…'?6:20,10,2).join(''),'…');
assert.equal(fitGraphText('abc',textMeasure,4).length,0,'Do not spill into a neighbouring column');
console.log('Comment visibility: available-space line count, lower-step clearance and measured ellipsis passed.');
